import type { PipelineEdge } from "./types";

export const pipelineEdges: PipelineEdge[] = [
  { id: "nanopore-reads-switch", source: "nanopore_reads", target: "reads", label: "if -np: NP", relation: "switch" },
  { id: "pacbio-reads-switch", source: "pacbio_reads", target: "reads", label: "if -pb: PB", relation: "switch" },
  { id: "reads-wrapper", source: "reads", target: "wrapper", label: "required fastq + mode", relation: "required" },
  { id: "diffcov-wrapper", source: "diffcov", target: "wrapper", label: "if --coverage", relation: "optional" },
  { id: "db-wrapper", source: "database_inputs", target: "wrapper", label: "proc DB paths / --install_databases", relation: "optional" },
  { id: "wrapper-metaflye", source: "wrapper", target: "assembly_metaflye", label: "default assembler", relation: "switch" },
  { id: "wrapper-metamdbg", source: "wrapper", target: "assembly_metamdbg", label: "if --use_metamdbg", relation: "switch" },
  { id: "wrapper-myloasm", source: "wrapper", target: "assembly_myloasm", label: "if --use_myloasm", relation: "switch" },
  { id: "wrapper-custom", source: "wrapper", target: "assembly_custom", label: "if --custom_assembly", relation: "switch" },
  { id: "metaflye-selected", source: "assembly_metaflye", target: "assembly_selected", label: "selected FASTA", relation: "merge" },
  { id: "metamdbg-selected", source: "assembly_metamdbg", target: "assembly_selected", label: "selected FASTA", relation: "merge" },
  { id: "myloasm-selected", source: "assembly_myloasm", target: "assembly_selected", label: "selected FASTA", relation: "merge" },
  { id: "custom-selected", source: "assembly_custom", target: "assembly_selected", label: "selected FASTA", relation: "merge" },
  { id: "selected-polishing", source: "assembly_selected", target: "polishing", label: "if Medaka TRUE and Nanopore", relation: "conditional" },
  { id: "selected-curation", source: "assembly_selected", target: "curation", label: "if curation TRUE", relation: "conditional", route: "top", lane: -180 },
  { id: "selected-filter-length", source: "assembly_selected", target: "filter_length", label: "if no Medaka and no curation", relation: "conditional" },
  { id: "polishing-curation", source: "polishing", target: "curation", label: "if curation TRUE", relation: "conditional" },
  { id: "polishing-filter-length", source: "polishing", target: "filter_length", label: "if curation FALSE", relation: "conditional", route: "top", lane: -230 },
  { id: "curation-filter-length", source: "curation", target: "filter_length", label: "curated assembly", relation: "required" },
  { id: "filter-length-tiara", source: "filter_length", target: "domain_tiara", label: "default: tiara_status TRUE", relation: "switch" },
  { id: "filter-length-whokaryote", source: "filter_length", target: "domain_whokaryote", label: "if --use_whokaryote", relation: "switch" },
  { id: "tiara-domain-split", source: "domain_tiara", target: "filter_domain", label: "selected header lists", relation: "merge" },
  { id: "whokaryote-domain-split", source: "domain_whokaryote", target: "filter_domain", label: "selected header lists", relation: "merge" },
  { id: "filter-domain-eukaryote", source: "filter_domain", target: "eukaryote_contigs", label: "side output: euk/unknown", relation: "fanout" },
  { id: "filter-length-coverage-map", source: "filter_length", target: "coverage_map", label: "automatic fan-out: mapping reference", relation: "fanout", route: "bottom", lane: 820 },
  { id: "filter-length-singleton-circular", source: "filter_length", target: "singleton_circular", label: "automatic fan-out: assembly info", relation: "fanout" },
  { id: "filter-length-singleton-linear", source: "filter_length", target: "singleton_linear", label: "automatic fan-out: assembly info", relation: "fanout", route: "bottom", lane: 760 },
  { id: "filter-length-taxonomy", source: "filter_length", target: "taxonomy", label: "automatic fan-out: assembly FASTA", relation: "fanout", route: "top", lane: -260 },
  { id: "filter-length-stats", source: "filter_length", target: "stats", label: "automatic fan-out: assembly stats", relation: "fanout", route: "bottom", lane: 910 },
  { id: "filter-domain-binning-prep", source: "filter_domain", target: "binning_prep", label: "prok contigs", relation: "required", route: "bottom", lane: 790 },
  { id: "filter-domain-singleton-circular", source: "filter_domain", target: "singleton_circular", label: "prok contigs", relation: "fanout" },
  { id: "singleton-circular-linear", source: "singleton_circular", target: "singleton_linear", label: "fallback guard", relation: "conditional" },
  { id: "singleton-circular-qc", source: "singleton_circular", target: "singletons", label: "circular candidates", relation: "merge" },
  { id: "singleton-linear-qc", source: "singleton_linear", target: "singletons", label: "linear/fallback candidates", relation: "merge" },
  { id: "singletons-coverage-prep", source: "singletons", target: "coverage_prep", label: "binned singleton IDs", relation: "fanout" },
  { id: "singletons-binning-prep", source: "singletons", target: "binning_prep", label: "exclude SMAG contigs", relation: "fanout" },
  { id: "singletons-mag-aggregate", source: "singletons", target: "mag_aggregate", label: "kept SMAGs", relation: "merge", route: "top", lane: -220 },
  { id: "reads-coverage-prep", source: "reads", target: "coverage_prep", label: "primary reads always prepended", relation: "required", route: "bottom", lane: 880 },
  { id: "diffcov-coverage-prep", source: "diffcov", target: "coverage_prep", label: "append rows if --coverage", relation: "optional", route: "bottom", lane: 940 },
  { id: "coverage-prep-map", source: "coverage_prep", target: "coverage_map", label: "one map job per read set", relation: "fanout" },
  { id: "coverage-map-aggregate", source: "coverage_map", target: "coverage_aggregate", label: "merge depth tables", relation: "merge" },
  { id: "coverage-aggregate-binning-prep", source: "coverage_aggregate", target: "binning_prep", label: "coverage matrices", relation: "required" },
  { id: "coverage-map-semibin2", source: "coverage_map", target: "semibin2", label: "BAMs", relation: "fanout", route: "top", lane: -180 },
  { id: "coverage-map-summary", source: "coverage_map", target: "summary_lite", label: "bin abundance", relation: "fanout", route: "bottom", lane: 850 },
  { id: "coverage-map-stats", source: "coverage_map", target: "stats", label: "mapping stats", relation: "fanout", route: "bottom", lane: 960 },
  { id: "binning-prep-metabat2", source: "binning_prep", target: "metabat2", label: "default/extended", relation: "conditional" },
  { id: "binning-prep-vamb", source: "binning_prep", target: "vamb", label: "default/extended", relation: "conditional" },
  { id: "binning-prep-semibin2", source: "binning_prep", target: "semibin2", label: "all binmodes", relation: "fanout" },
  { id: "binning-prep-comebin", source: "binning_prep", target: "comebin", label: "extended round 2", relation: "conditional" },
  { id: "metabat2-candidate-bins", source: "metabat2", target: "candidate_bins", label: "MetaBAT2 -> partitions", relation: "merge", route: "top", lane: -130 },
  { id: "vamb-clustering", source: "vamb", target: "vamb_clustering", label: "latent z_i", relation: "required" },
  { id: "vamb-clustering-candidate-bins", source: "vamb_clustering", target: "candidate_bins", label: "VAMB -> latent bins", relation: "merge" },
  { id: "semibin2-clustering", source: "semibin2", target: "semibin2_clustering", label: "embedding z_i", relation: "required" },
  { id: "semibin2-clustering-candidate-bins", source: "semibin2_clustering", target: "candidate_bins", label: "SemiBin2 -> DBSCAN ensemble bins", relation: "merge" },
  { id: "comebin-clustering", source: "comebin", target: "comebin_clustering", label: "multi-view embeddings", relation: "required" },
  { id: "comebin-clustering-candidate-bins", source: "comebin_clustering", target: "candidate_bins", label: "COMEBin -> Leiden bins", relation: "merge" },
  { id: "candidate-bins-binette", source: "candidate_bins", target: "binette", label: "default / extended R1,R3", relation: "conditional" },
  { id: "candidate-bins-router", source: "candidate_bins", target: "binmode_router", label: "fast / extended R2,R4 direct", relation: "switch" },
  { id: "binette-router", source: "binette", target: "binmode_router", label: "default / extended refined", relation: "switch" },
  { id: "router-qc", source: "binmode_router", target: "binning_qc", label: "selected candidate source", relation: "required" },
  { id: "qc-mag-aggregate", source: "binning_qc", target: "mag_aggregate", label: "kept round bins", relation: "merge" },
  { id: "mag-aggregate-final-checkm", source: "mag_aggregate", target: "checkm_qc2", label: "all candidate MAGs", relation: "required" },
  { id: "checkm-summary", source: "checkm_qc2", target: "summary_lite", label: "final kept bins", relation: "required" },
  { id: "checkm-taxonomy", source: "checkm_qc2", target: "taxonomy", label: "MAG FASTAs", relation: "fanout" },
  { id: "checkm-annotation", source: "checkm_qc2", target: "annotation", label: "MAG FASTAs", relation: "fanout" },
  { id: "checkm-extraqc", source: "checkm_qc2", target: "extraqc", label: "MAG FASTAs", relation: "fanout", route: "top", lane: -180 },
  { id: "summary-taxonomy", source: "summary_lite", target: "taxonomy", label: "contig/bin map", relation: "fanout" },
  { id: "summary-annotation", source: "summary_lite", target: "annotation", label: "bin list", relation: "fanout" },
  { id: "summary-extraqc", source: "summary_lite", target: "extraqc", label: "bin list", relation: "fanout" },
  { id: "summary-stats", source: "summary_lite", target: "stats", label: "summary inputs", relation: "fanout" },
  { id: "taxonomy-final", source: "taxonomy", target: "finalise_proc", label: "taxonomy tables", relation: "merge" },
  { id: "annotation-final", source: "annotation", target: "finalise_proc", label: "annotation tables", relation: "merge" },
  { id: "extraqc-final", source: "extraqc", target: "finalise_proc", label: "extra QC tables", relation: "merge" },
  { id: "stats-final", source: "stats", target: "finalise_proc", label: "stats tables", relation: "merge" }
];
